function Mania() {

    Manias = [
       "Ablutomarúa: Interés excesivo en la limpieza personal",
       "Aboulomanía: Indecisión patológica",
       "Acluomanía: Gusto excesivo por la oscuridad",
       "Acromanía (altura): Obsesión por los lugares altos",
       "Agatomanía: Amabilidad pato lógica",
       "Agromanía: Deseo intenso de estar en espacios abiertos",
       "Aicmomanía: Obsesión por los objetos puntiagudos o afilados",
       "Ailuromanía: Gusto excesivo por los gatos",
       "Algomanía: Obsesión por el dolor",
       "Aliomanía: Obsesión por el ajo",
       "Amaxomanía: Obsesión por los vehículos",
       "Amenomanía: Alegría irracional",
       "Antomanía: Obsesión por las flores",
       "Aritmomanía: Preocupación obsesiva por los números",
       "Asoticamanía: Gasto o despilfarro impulsivo y autodestructivo",
       "Automanía: Gusto excesivo por la soledad",
       "Balletomanía: Entu siasmo anormal por el ballet",
       "Bibliocleptomania: Robo compulsivo de libros",
       "Bibliomarúa: Obsesión por los libros y/o leer",
       "Bruxomanía: Compulsión por rechinar los dientes",
       "Cacodemomania: Creencia patológica de estar poseído por un espíritu maligno",
       "Calomanía: Obsesión por la propia belleza",
       "Cartacoethes: Compulsión incontrolable de ver mapas por todas partes",
       "Catapedamanía: Obsesión por saltar desde lugares el!lvados",
       "Ceirnatomanía: Deseo anormal por el frio y/o las cosas frías",
       "Clazomanía: Compulsión irracional por gritar",
       "Cleptomanía: Compulsión irracional por robar",
       "Clinomanía: Gusto excesivo por estar en cama",
       "Coimetromanía: Obsesión por los cementerios",
       "Coloromanía: Obsesión por un color determinado",
       "Coreomanía: Obsesión o frenesí incontrolable por bailar",
       "Coulromanía: Obsesión por los payasos",
       "Countennanía: Compulsion por experimentar situaciones aterradoras",
       "Dacnornanía: Obsesión por matar",
       "Demonomanía: Creencia patológica de estar poseído por demonios",
       "Dermatilomanía: Compulsión por arrancarse la piel",
       "Dikemanía: Obsesión por ver que se hace justicia",
       "Dipsomanía: Ansia anormal por consumir alcohol",
       "Doramanía: Obsesión por poseer pieles",
       "Doromanía: Obsesión por hacer regalos",
       "Drapetornanía: Compulsión por fugarse",
       "Ecdemiornanía: Compulsión po vagabundear",
       "Egomanía: Actitud ególatra irracional u obsesión por uno mismo",
       "Empleomanía: Ansia irracional por ocupar cargos públicos",
       "Enosimanía: Creencia patológica de haber pecado",
       "Epistemomanía: Obsesión por adquirir conocimientos",
       "Eremiomanía: Compulsión por permanecer inmóbil",
       "Eteromanía: Ansia de éter",
       "Fasmomanía: Obsesión por los fantasmas",
       "Fonomanía: Tendencia patológica al asesinato",
       "Fotomanía: Deseo patológico de luz",
       "Garabatornanía: Obsesion por garabatear o pintarrajear",
       "Garnomanía: Obsesión por hacer propuestas de matrimonio extrañas",
       "Geliomanía: Compulsión incontrolable por reir",
       "Gimnomanía: Compulsión por desnudarse",
       "Goetornanía: Obsesión por las brujas y la brujería",
       "Grafomania: Obsesión por escribirlo todo",
       "Habrom anía: Tendencia anormal a crear delirios placenteros (en sustitución de la realidad)",
       "Helmintomanía: Gusto excesivo por los gusanos",
       "Hidromanía: Ansia irracional por beber agua",
       "Iconomanía: Obsesión por los iconos o los retratos",
       "Ictiomanía: Obsesión por los peces",
       "ldolomanía: Obsesión o devocion a un idolo",
       "Infornanía: Devocion excesiva por la acumulacion de datos",
       "Ligiromania: Compulsion incontrolabrle por hacer ruido intensos o estridentes",
       "Linonomania: Obsesion por las cuerdas",
       "Lipomanía: Tendencia anormal hacia la melancolia",
       "Loteromania: Deseo excesivo de participar en sorteos",
       "Megalitomania: Tendencia anormal a tener ideas extrañas en presencia de menhires o circulos de piedra",
       "Melomania: Obsesion por la musica o por una melodia determinada",
       "Metromania: Deseo insaciable de escribir en verso",
       "Misomanía: Odio a todo, obsesion por odiar a un sujeto o grupo",
       "Mitomanía: Mentir o exagerar hasta un punto anormal",
       "Monomanía: Obsesion anormal por un único pensamiento o idea",
       "Nosomanía: Delirio de padecer una enfermedad imaginaria",
       "Notomanía: Compulsion por registrarlo todo(por ejemplo sacar muchas fotos)",
       "Onomanía: Obsesion por los nombres(de lugares, personas, lugares o cosas)",
       "Onomatonomanía: Deseo irrefrenable de repetir determinadas palabras",
       "Onicotolomanía: Compulsion por morderse o arrancarse las uñas",
       "Opsomanía: Amor anormal por cierto tipo de comida",
       "Paramanía: Placer anormal por quejarse",
       "Personamanía: Compulsion por llevar mascara",
       "Piromanía: Compulsion por prender fuego",
       "Planomanía: Deseo anormal de desobeder las normas sociales",
       "Plutomanía: Deseo obsesivo de dinero",
       "Preguntamanía: Necesidad compulsiva de hacer preguntas",
       "Pseudomanía: Compulsion irracional por mentir",
       "Rinotilexomanía: Compulsion por hurgarse la nariz",
       "Sideroclromomanía: Fascinacion intensa por los trenes o el viaje en ferrocarril",
       "Sofomanía: Delirios de que uno es increiblemente inteligente",
       "Tanatomanía: Obsesion por la muerte o el suicidio",
       "Tecnomanía: Obsesion por las nuevas tecnologias",
       "Teomanía: La creencia de ser un dios",
       "Tiflomanía: Ceguera patologica",
       "Titilomanía: Compuslion por rascarse",
       "Tomomanía: Gusto irracional por practicar la cirugía",
       "Tricotilomanía: Ansia por tirarse del pelo",
       "Xenomanía: Obsesion por los extranjeros",
       "Zoomanía: Amor insano hacia los animales",
      
    ] 

    Manias_leght = Math.floor(Math.random() * Manias.length)
    document.getElementById("resultE").innerHTML =
    "<h1>Manía</h1><h2>"+Manias[Manias_leght]+"<h2>"


}