function Fobias(){

         var Fobia =[ 
         "Ablutofobia:Miedo a bañarse", 
         "Acrofobia: Alturas", 
         "Aerofobia: Volar", 
         "Agorafobia: miedo a espacios con límites indefinidos y abiertos",
         "Alektorofobia: Miedo a las Gallinas",
         "Aliumfobia: Miedo / aversión irracional y exacerbado hacia el ajo",
         "Amaxofobia: Miedo a conducir",
         "Ancraofobia: Miedo al viento",
         "Androfobia: Miedo a los hombres",
         "Anglofobia: Miedo a Inglaterra, a la cultura británica",
         "Antofobia: Miedo a las flores",
         "Apotemnofobia: Miedo a las personas que tienen miembros amputados",
         "Arachnofobia: Miedo a las arañas",
         "Astrafobia: Miedo a los relámpagos",
         "Atefobia: Miedo a las ruinas o reliquias",
         "Aulofobia: Miedo a las flautas",
         "Bacteriofobia: Miedo a las bacterias",
         "Balistofobia: Miedo a los proyectiles o las balas",
         "Basofobia: Miedo a caerse",
         "Bibliofobia: Miedo a Jos li bros",
         "Botanofobia: Miedo a las plantas",
         "Caliginefobia: Miedo a las mujeres hermosas",
         "Catsaridafobia: Miedo a las cucarachas",
         "Cheimafobia: Miedo al frío",
         "Cinofobia: Miedo a los perros",
         "Claustrofobia: Miedo a los espacios cerrados",
         "Coulrofobia: Miedo a los payasos",
         "Cronomentrofobia: Miedo a los relojes",
         "Demofobia: Miedo a las multitudes",
         "Demonofobia: Miedo a los espíritus y los demonios",
         "Dentofobia: Miedo a los dentistas",
         "Disposofobia: Miedo a tirar cosas",
         "Dorafobia: Miedo a las pieles",
         "Dromofobia: Miedo a cruzar la calle",
         "Eclesiofobia: Miedo a la iglesia",
         "Eisoptrofobia: Miedo a los espejos",
         "Enetofobia: Miedo a las agujas o los alfileres",
         "Entomofobia: Miedo a los insectos",
         "Escotofobia: Miedo a la oscuridad o a la noche",
         "Estenofobia: Miedo a las cosas o lugares es trechos",
         "Estenofobia: Miedo a las cosas o lugares es trechos",
         "Fagofobia: Miedo a tragar sienten que se atragantaran",
         "Farmacofobia: Miedo a los medi camentos",
         "Fasmofobia: Miedo a los fantasmas",
         "Felinofobia: Miedo a los gatos",
         "Fenogofobia: Miedo a la luz del día",
         "Gefirofobia: Miedo a cruzar los puentes",
         "Gerontofobia: Miedo a los ancianos o a envejecer",
         "Ginofobia: Miedo a las mujeres",
         "Hafefobia: Miedo a ser tocado",
         "Hamartofobia: Miedo a pecar",
         "Hematofobia: Miedo a la sangre",
         "Herpetofobia: Miedo a los reptiles",
         "Hidrofobia: Miedo al agua",
         "Hipnofobia: Miedo a dormir o a ser hipnotizado",
         "Homiclofobia: Miedo a la niebla",
         "Hoplofobia: Miedo a las armas de fuego",
         "Iatrofobia: Miedo a los médicos",
         "Ictiofobia: Miedo a los peces",
         "Lacanofobia: Miedo a los vegetales",
         "Ligirofobia:. Miedo a los ruidos fuertes",
         "Limnofobia: Miedo a los lagos",
         "Mecanofobia: Miedo a las máquinas o a los mecanismos",
         "Megalofobia: Mi edo a los objetos grandes",
         "Merintofobia: Miedo a ser atado o amarrado",
         "Meteomfobia: Miedo a los meteoros y meteoritos",
         "Misofobia: Miedo a la suciedad o la contaminación",
         "Mixofobia: Asco a la gente de otra nacionalidad color o estatus social mas bajo",
         "Monofobia: Miedo a estar solo",
         "Necrofobia: :Miedo a la muerte y a las cosas muertas",
         "Octofobia: Miedo al numero 8",
         "Odontofobia: Miedo a los clientes",
         "Ofidiofobia: Miedo a las serpientes",
         "Oneirofobia: Miedo a los sueños",
         "Onomatofobia: Miedo a escuchar determinada palabra o palabras",
         "Ornitofobia: Miedo a los pájaros",
         "Parasitofobia: Miedo a los parásitos",
         "Pediofobia: Miedo a las muñecas",
         "Pirofobia: Miedo al fuego",
         "Pogonofobia: Miedo a las barbas",
         "Potamofobia: Miedo a los ríos",
         "Potofobia: Miedo al alcohol o a las bebidas alcohólicas",
         "Rabdofobia: Miedo a ser severamente castigado",
         "Selenofobia: Miedo a la luna",
         "Siderodromofobia: Miedo a viajar en tren",
         "Siderofobia: Miedo a las estrellas",
         "Simetrofobia: Miedo a la simetría",
         "Talasofobia: Miedo al mar",
         "Tapefobia: Miedo a los cementerios o a ser enterrado vivo",
         "Taurofobia: Miedo a los toros",
         "Telefonofobia: Miedo a los teléfonos",
         "Teratofobia: Miedo a los monstruos",
         "Tomofobia: Miedo a las operaciones quirúrgicas",
         "Triscadecafobia: Miedo al número 13",
         "Vestifobia: Miedo a la ropa",
         "Wiccafobia: Miedo a las brujas y a la brujeria",
         "Xantofobia: Miedo al color amarill o a la palabra amarillo",
         "Xenofobia: Miedo a los extraños o a los extranjeros",
         "Xenoglosofobia: Miedo a las lenguas extranjeras",
         "Zoofobia: Miedo a los animales"
                   
         ];

         var Fobia_leght = Math.floor(Math.random() * Fobia.length);
         document.getElementById("resultE").innerHTML = 
         "<h1>Fobia :</h1>"+"<h2>"+Fobia[Fobia_leght]+"</h2>"
        //  document.getElementById("resultE").innerHTML =
        //  "<h1>Soda:</h1>"+"<h2>"+Fobia[Fobia_leght]+"</h2>"




}